Adding unit tests for the graph; updating the pre-commit hook to run unit tests on commit
Loading Dictionary
Avg sz:29.807053
Words: 999999	Edges: 3164481
Num Buckets: 8388608
buildIndex time (sec): 1.721617
buildAdjList time (sec): 2.997855
LoadDictionary time (sec): 4.921468

Profile: ./profiles/master/2020-01-26_11-28-38

File: wordladder
Type: alloc_space
Time: Jan 26, 2020 at 11:28am (EST)
Showing nodes accounting for 811.19MB, 99.94% of 811.69MB total
Dropped 3 nodes (cum <= 4.06MB)
      flat  flat%   sum%        cum   cum%
  370.14MB 45.60% 45.60%   370.14MB 45.60%  main.(*Graph).buildAdjList
     192MB 23.65% 69.26%      192MB 23.65%  main.newIndex
  156.05MB 19.23% 88.48%   811.19MB 99.94%  main.LoadDictionary
      93MB 11.46% 99.94%       93MB 11.46%  main.(*index).add
         0     0% 99.94%   811.19MB 99.94%  main.main
         0     0% 99.94%   811.19MB 99.94%  runtime.main

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -17,12 +17,23 @@ done;
 
 if [ "${hasGo}" == "NO" ]
 then
-    echo "Skipping performance test: no Go files modified"
+    echo "Skipping tests: no Go files modified"
     exit 0
-else
-    echo "Running performance test"
 fi
 
+# Run the unit tests, if any fail, then do not allow the commit to continue
+echo "Running unit tests"
+TEST_RESULTS="/tmp/wordladder_test_results.txt"
+go test ./... > "${TEST_RESULTS}"
+if [ "$?" -ne "0" ]
+then
+    echo "One or more unit tests failed, printing test output below: "
+    cat "${TEST_RESULTS}"
+    exit 1
+fi
+
+# Run wordladder on a large dictionary and profile the performance
+echo "Running performance tests"
 BRANCH_NAME=$(git symbolic-ref --short HEAD)
 TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
 PROFILE_PATH="./profiles/${BRANCH_NAME}/${TIMESTAMP}"
